// ============================================================================
// main.js — entry point for the 3D portfolio world (world.html).
//
// Loads assets/world/world.glb (Draco-compressed, generated by
// blender/build_world.py) + assets/world/cam_path.json, then hands control
// to ScrollRig (camera), fx (shaders/ambience) and Interactions (everything
// clickable). Scene/interaction contract: blender/PIPELINE.md.
//
// Draco, not meshopt: gltf-transform's meshopt/quantize pass silently
// corrupts translation+scale on every instanced node (verified — see
// PIPELINE.md §5), so compression uses `gltf-transform draco` instead.
// ============================================================================
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';
import { MeshoptDecoder } from 'three/addons/libs/meshopt_decoder.module.js';
import { ScrollRig } from './ScrollRig.js';
import { setupFX } from './fx.js';
import { Interactions } from './interactions.js';
import { TrainRide } from './TrainRide.js';

// provisional fly camera (toggle with F): WASD + Q/E, drag to look, Shift fast
class Freecam {
    constructor(camera, dom) {
        this.camera = camera;
        this.enabled = false;
        this.keys = {};
        this.euler = new THREE.Euler(0, 0, 0, 'YXZ');
        this._drag = null;
        window.addEventListener('keydown', (e) => { this.keys[e.code] = true; });
        window.addEventListener('keyup', (e) => { this.keys[e.code] = false; });
        dom.addEventListener('pointerdown', (e) => {
            if (this.enabled) this._drag = [e.clientX, e.clientY];
        });
        window.addEventListener('pointerup', () => { this._drag = null; });
        dom.addEventListener('pointermove', (e) => {
            if (!this.enabled || !this._drag) return;
            this.euler.y -= (e.clientX - this._drag[0]) * 0.0035;
            this.euler.x -= (e.clientY - this._drag[1]) * 0.0035;
            this.euler.x = Math.max(-1.5, Math.min(1.5, this.euler.x));
            this._drag = [e.clientX, e.clientY];
        });
    }

    toggle() {
        this.enabled = !this.enabled;
        if (this.enabled) this.euler.setFromQuaternion(this.camera.quaternion, 'YXZ');
        return this.enabled;
    }

    update(dt) {
        const k = this.keys;
        const speed = (k.ShiftLeft || k.ShiftRight ? 34 : 9) * dt;
        const dir = new THREE.Vector3(
            (k.KeyD ? 1 : 0) - (k.KeyA ? 1 : 0),
            (k.KeyE ? 1 : 0) - (k.KeyQ ? 1 : 0),
            (k.KeyS ? 1 : 0) - (k.KeyW ? 1 : 0),
        );
        this.camera.quaternion.setFromEuler(this.euler);
        dir.applyQuaternion(this.camera.quaternion);
        this.camera.position.addScaledVector(dir, speed);
    }
}

const container = document.getElementById('canvas3d');
const splash = document.getElementById('splash');
const enterBtn = document.getElementById('btn-enter');
const loadFill = document.getElementById('load-bar-fill');

const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: 'high-performance' });
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.0;
container.appendChild(renderer.domElement);

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(55, window.innerWidth / window.innerHeight, 0.08, 600);
scene.add(camera);

window.addEventListener('resize', () => {
    camera.aspect = window.innerWidth / window.innerHeight;
    camera.updateProjectionMatrix();
    renderer.setSize(window.innerWidth, window.innerHeight);
});

// ---------------------------------------------------------------- loading --
const manager = new THREE.LoadingManager();
manager.onProgress = (_url, loaded, total) => {
    loadFill.style.width = `${Math.round((loaded / total) * 100)}%`;
};

const dracoLoader = new DRACOLoader(manager);
dracoLoader.setDecoderPath('./src/vendor/three/addons/libs/draco/gltf/');

const loader = new GLTFLoader(manager);
loader.setDRACOLoader(dracoLoader);
loader.setMeshoptDecoder(MeshoptDecoder);

// The four sky panoramas and the light rig that goes with them are baked out
// of world.blend by blender/sky_and_light.py — see PIPELINE.md §4.2. If they
// are missing the world still lights itself from fx.js' fallback rig, so a
// failed sky fetch must never take the whole scene down with it.
const imageLoader = new THREE.ImageLoader(manager);
const loadSky = fetch('./assets/world/sky_rig.json')
    .then((r) => (r.ok ? r.json() : Promise.reject(new Error(r.status))))
    .then(async (skyRig) => {
        const images = {};
        await Promise.all(skyRig.zones.map((z) =>
            new Promise((res) => imageLoader.load(
                z.texture, (img) => { images[z.key] = img; res(); },
                undefined, () => res()))));
        return { skyRig, images };
    })
    .catch((err) => {
        console.warn('[world] sky rig unavailable, using fallback ambience', err);
        return { skyRig: null, images: null };
    });

Promise.all([
    new Promise((res, rej) => loader.load('./assets/world/world.glb', res, undefined, rej)),
    fetch('./assets/world/cam_path.json').then((r) => r.json()),
    loadSky,
]).then(([gltf, pathData, sky]) => init(gltf, pathData, sky))
    .catch((err) => {
        console.error('[world] load failed', err);
        enterBtn.textContent = 'FEHLER BEIM LADEN';
    });

// ------------------------------------------------------------------- init --
function init(gltf, pathData, sky) {
    scene.add(gltf.scene);

    // camera waypoint anchors (path_u) from the GLB extras
    const anchors = {};
    gltf.scene.traverse((o) => {
        if (o.userData && o.userData.camera_waypoint) {
            anchors[o.userData.camera_waypoint] = o.userData.path_u;
        }
    });

    const rig = new ScrollRig(pathData, anchors);
    // exact framings from the cam_wp* empties. Blender empties keep Z-up
    // object semantics through the exporter (unlike cameras), so their
    // "look" axis lands on local -Y here; rotate -90° about X to make it
    // a three.js camera orientation (-Z forward, +Y up).
    const EMPTY_FIX = new THREE.Quaternion().setFromAxisAngle(
        new THREE.Vector3(1, 0, 0), -Math.PI / 2);
    const stopPoses = {};
    gltf.scene.updateMatrixWorld(true);
    gltf.scene.traverse((o) => {
        const wp = o.userData && o.userData.camera_waypoint;
        if (wp) {
            stopPoses[wp] = {
                pos: o.getWorldPosition(new THREE.Vector3()),
                quat: o.getWorldQuaternion(new THREE.Quaternion()).multiply(EMPTY_FIX),
            };
        }
    });
    rig.setStopPoses(stopPoses);
    const fx = setupFX(scene, renderer, gltf.scene, anchors, rig,
                       sky && sky.skyRig, sky && sky.images);
    const mixer = new THREE.AnimationMixer(gltf.scene);
    const inter = new Interactions({
        scene, camera, rig, mixer,
        clips: gltf.animations.filter((c) => c.name !== 'cam_fly_through'),
        dom: renderer.domElement,
        lampPool: fx.lampPool,
    });
    const ride = new TrainRide(scene, rig, inter.actions);
    const freecam = new Freecam(camera, renderer.domElement);
    window.addEventListener('keydown', (e) => {
        if (e.code === 'KeyF') {
            const on = freecam.toggle();
            rig.inputEnabled = !on;
            inter.toast(on ? 'Freecam an — WASD/QE + Ziehen, F beendet'
                           : 'Freecam aus');
        }
    });

    rig.onFirstMove = () => document.body.classList.add('moved');

    // debug / test hook
    window.__world = { rig, scene, camera, renderer, fx, inter, ride, freecam, THREE };

    const clock = new THREE.Clock();
    let started = false;

    function tick() {
        const dt = Math.min(clock.getDelta(), 0.05);
        const t = clock.elapsedTime;
        rig.update(dt);
        ride.update(t);
        if (freecam.enabled) {
            freecam.update(dt);
        } else {
            camera.position.copy(rig.pos);
            camera.quaternion.copy(rig.quat);
        }
        mixer.update(dt);
        fx.update(t, rig.u, camera.position);
        if (started) inter.update(dt);
        renderer.render(scene, camera);
        requestAnimationFrame(tick);
    }
    tick();

    enterBtn.disabled = false;
    enterBtn.textContent = 'EINTRETEN';
    enterBtn.addEventListener('click', () => {
        splash.classList.add('hidden');
        document.body.classList.add('started');
        started = true;
        rig.attach(renderer.domElement);
        rig.goToS(rig.stops.find((s) => s.name === 'home').s);   // intro drift
    }, { once: true });
}
